name: Release Obsidian Theme

on:
  push:
    tags:
      - '*' # Runs on every pushed tag

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            theme.css
            manifest.json

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            theme.css
            manifest.json
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
